frontend/__init__.py
from flask import Flask

def create_frontend():
    app = Flask(__name__)

    from .routes.index_bp import main
    app.register_blueprint(main)

    from .routes.auth.auth_bp import auth_bp
    app.register_blueprint(auth_bp)

    from .routes.pool_bp import pool_bp
    app.register_blueprint(pool_bp)

    return app

frontend/routes/index_bp.py
from flask import Blueprint, render_template, request, redirect, url_for
import os

from dotenv import load_dotenv
load_dotenv()

main = Blueprint('main', __name__)

from ..utils.axios_client import Axios
axios = Axios(base_url=os.getenv('BACKEND_HOST'), headers={'Content-Type': 'application/json'})
        
@main.route("/profile", methods=["GET", "POST"])
def profile():
    profiles = axios.get('/ppp/profiles').json()
    if request.method == 'GET':
        return render_template('profile/profiles.html', profiles=profiles)
    elif request.method == 'POST':
        data = request.form.to_dict()
        response = axios.post('/ppp/profile', json=data)
        if response.status_code == 201:
            profiles = axios.get('/ppp/profiles').json()
            return redirect(url_for('main.profile', profiles=profiles))
        else:
            return render_template('profile/profile.html', error=response.json().get('error', 'Unknown error'))

frontend/routes/pool_bp.py
from flask import Blueprint, render_template, request, redirect, url_for
import os

from dotenv import load_dotenv
load_dotenv()

pool_bp = Blueprint('pools', __name__, url_prefix='/pools')

from ..utils.axios_client import Axios
axios = Axios(base_url=os.getenv('BACKEND_HOST'), headers={'Content-Type': 'application/json'})

@pool_bp.route('/', methods=['GET', 'POST'])
def pools():
    pools = axios.get('/ppp/ip-pools').json()
    if request.method == 'GET':
        return render_template('pool/pools.html', pools=pools)
    elif request.method == 'POST':
        data = request.form.to_dict()
        response = axios.post('/ppp/ip-pool', json=data)
        if response.status_code == 201:
            pools = axios.get('/ppp/ip-pools').json()
            return redirect(url_for('pool_bp.pools', pools=pools))
        else:
            return render_template('pool/ip_pool.html', error=response.json().get('error', 'Unknown error'))

frontend/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{% block title %} {% endblock title %} | EasyConnect</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    {% block content %} {% endblock content %}
    <script src="" async defer></script>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  </body>
</html>

frontend/templates/error.html
{% extends "base.html" %} {% block title %}Error{% endblock %} {% block content
%}
<h1 class="text-red-600">Error</h1>
<p class="text-gray-700">An error occurred while processing your request.</p>
{% endblock %}

frontend/templates/pool/pool_form.html
<h1>Create PPP Pool</h1>
<form action="{{ url_for('pools.pools') }}" method="POST">
  <label>Name:</label><br />
  <input type="text" name="name" required /><br /><br />

  <label>Ranges:</label><br />
  <input type="text" name="ranges" /><br /><br />

  <button type="submit">Create Profile</button>
</form>

frontend/templates/pool/pools.html
{% extends "./base.html" %} {% block title %}IP Pool{% endblock %} {% block
content %}
<div class="container">
  <h1>IP Pool</h1>
  <p>Manage your IP pool here.</p>
  {% include "./pool/pool_form.html" %}
  <h2 class="mt-4">Current Pools</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Pool Name</th>
        <th>Ranges</th>
      </tr>
    </thead>
    <tbody>
      {% for pool in pools %}
      <tr>
        <td>{{ pool["name"] }}</td>
        <td>{{ pool["ranges"] }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

frontend/templates/profile/profiles.html
{% extends "./base.html" %} {% block title %}IP Pool{% endblock %} {% block
content %}
<div class="container">
  <h2 class="mt-4">Current Profiles</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Profile Name</th>
        <th>Local Address</th>
        <th>Remote Address</th>
        <th>DNS Server 1</th>
        <th>DNS Server 2</th>
        <th>Only One</th>
        <th>Bandwitdh Limit</th>
      </tr>
    </thead>
    <tbody>
      {% for profile in profiles %}
      <tr>
        <td>{{ profile["name"] }}</td>
        <td>{{ profile["local-address"] }}</td>
        <td>{{ profile["remote-address"] }}</td>
        {% if profile["dns-server"] %}
        <td>{{ profile["dns-server"].split(",")[0] }}</td>
        <td>{{ profile["dns-server"].split(",")[1] }}</td>
        {% else %}
        <td>N/A</td>
        <td>N/A</td>
        {% endif %}
        <td>{{ profile["only-one"] }}</td>
        <td>{{ profile["rate-limit"] }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}